---
- name: Include setup tasks
  include_tasks:
    file: linux.yml
  loop: "{{ bash_it_users }}"
  loop_control:
    loop_var: outer_item
  when: ansible_distribution != "MacOSX"

- name: Include setup tasks
  include_tasks:
    file: macos.yml
  loop: "{{ bash_it_users }}"
  loop_control:
    loop_var: outer_item
  when: ansible_distribution == "MacOSX"
